#!/bin/bash

#
# ownCloud Android scenario tests
#
# @author Jesus Recio (@jesmrec)
# Copyright (C) 2020 ownCloud GmbH.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

help()
{
   echo ""
   echo "Usage: $0 -s <ownCloud Server URL> -t <filter> -a <Appium Server URL> -d <device UID> "
   echo ""
   echo -e "\t-s (mandatory) URL of ownCloud server to test against"
   echo -e "\t-a (optional) Appium server URL. if Appium Server is not specified, will be used \"localhost:4723/wd/hub\""
   echo -e "\t-t (optional) Filter. F. ex: @createfolder will send only tests tagged with such label. Tags are allowed to concatenate, sepparated by \",\". It is also allowed to use a classpath to execute all the test in such class"
   echo -e "\t-d (optional) In case of several devices attached, tests will be sent against the UID set in this option"
   echo ""
   exit 1 
}

while getopts ":t:a:s:d:h" opt; do
  case $opt in
    t) tags="$OPTARG"
    ;;
    a) appium="$OPTARG"
    ;;
    s) oc="$OPTARG"
    ;;
    d) device="$OPTARG"
    ;;
    h) help
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

if [ $# -eq 0 ]
then
  help
elif [ -z "$oc" ]
then
   echo "ownCloud Server URL is missing";
   help
fi

echo "Appium server: $appium"
echo "oC server: $oc"
echo "tags: $tags"
echo "device: $device"

if [ -z "$tags" ]
then
 ./gradlew clean test aggregate \
  --info \
  -Dappium=$appium \
  -Ddevice=$device \
  -Dserver=$oc
else
  ./gradlew clean test aggregate \
  --info \
  -Dcucumber.options="--tags $tags" \
  -Dappium=$appium \
  -Ddevice=$device \
  -Dserver=$oc
fi
